version: '3.0'

services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow

    slurm:
        image: kgutwin/airflow-drmaa-dev
        hostname: slurm-master
        volumes:
            #- data-volume:/usr/local/airflow/dags
            - ~/docker-airflow/dags:/usr/local/airflow/dags
            - ~/docker-airflow/logs:/usr/local/airflow/logs
            - munge-key:/etc/munge
            - slurm-shared:/shared
            - ~/github/incubator-airflow:/usr/local/airflow/src
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        command: slurm-master

    webserver:
        image: kgutwin/airflow-drmaa-dev
        volumes:
            #- data-volume:/usr/local/airflow/dags
            - ~/docker-airflow/dags:/usr/local/airflow/dags
            - ~/docker-airflow/logs:/usr/local/airflow/logs
            - munge-key:/root/munge-key
            - slurm-shared:/shared
            - ~/github/incubator-airflow:/usr/local/airflow/src
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        ports:
            - "8080:8080"
        links:
            - mysql:mysql
            - slurm:slurm-master
            - scheduler:scheduler
        command: webserver

    scheduler:
        image: kgutwin/airflow-drmaa-dev
        volumes:
            #- data-volume:/usr/local/airflow/dags
            - ~/docker-airflow/dags:/usr/local/airflow/dags
            - ~/docker-airflow/logs:/usr/local/airflow/logs
            - munge-key:/root/munge-key
            - slurm-shared:/shared
            - ~/github/incubator-airflow:/usr/local/airflow/src
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        links:
            - mysql:mysql
            - slurm:slurm-master
        command: scheduler

volumes:
    data-volume:
    munge-key:
    slurm-shared:
